version: 2

multi-ecosystem-groups:
  all-dependencies:
    target-branch: dev
    schedule:
      interval: weekly

updates:
  - package-ecosystem: npm
    directory: /
    patterns:
      - "*"
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
